# Site settings
title: Coder's Quandary
header-img: img/home-bg.png
email: avery.c.broderick@gmail.com
copyright_name: averybroderick
description: > # this means to ignore newlines until "baseurl:"
  My journey through the Flatiron School's Online Web Dev Curriculum
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  averybroderick
learn_profile: averybroderick
email_username: avery.c.broderick@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
